name: dqn-flappy-bird
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pyyaml
  - pytorch
  - torchvision
  - cpuonly               # remove this line and add cudatoolkit if you want GPU support
  - gymnasium>=1.0
  - opencv
  - pip
  - pip:
    - flappy-bird-gymnasium
