cartpole1:
  env_id: CartPole-v1
  replay_memory_size: 10000
  batch_size: 32
  epsilon_init: 1.0
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  network_sync_rate: 10
  learning_rate_a: 0.001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 10
  enable_double_dqn: False

flappybird1:
  env_id: FlappyBird-v0
  replay_memory_size: 10000
  batch_size: 32
  epsilon_init: 1.0
  epsilon_decay: 0.99995
  epsilon_min: 0.05
  network_sync_rate: 10
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: False

flappybird2:
  env_id: FlappyBird-v0
  replay_memory_size: 10000
  batch_size: 32
  epsilon_init: 1.0
  epsilon_decay: 0.99999
  epsilon_min: 0.05
  network_sync_rate: 10
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: False

flappybird3:
  env_id: FlappyBird-v0
  replay_memory_size: 10000
  batch_size: 32
  epsilon_init: 1.0
  epsilon_decay: 0.99995
  epsilon_min: 0.05
  network_sync_rate: 500
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: False


flappybird4:
  env_id: FlappyBird-v0
  replay_memory_size: 10000
  batch_size: 32
  epsilon_init: 1.0
  epsilon_decay: 0.999995
  epsilon_min: 0.05
  network_sync_rate: 500
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: False

flappybird5:
  env_id: FlappyBird-v0
  replay_memory_size: 50000
  batch_size: 64
  epsilon_init: 1.0
  epsilon_decay: 0.999995
  epsilon_min: 0.02
  network_sync_rate: 500
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: False

flappybird6:
  env_id: FlappyBird-v0
  replay_memory_size: 50000
  batch_size: 64
  epsilon_init: 1.0
  epsilon_decay: 0.999995
  epsilon_min: 0.01
  network_sync_rate: 500
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: False

flappybird7:
  env_id: FlappyBird-v0
  replay_memory_size: 50000
  batch_size: 64
  epsilon_init: 1.0
  epsilon_decay: 0.999995
  epsilon_min: 0.02
  network_sync_rate: 500
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: True

flappybird8:
  env_id: FlappyBird-v0
  replay_memory_size: 200000
  batch_size: 64
  epsilon_init: 1.0
  epsilon_decay: 0.999995
  epsilon_min: 0.02
  network_sync_rate: 500
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: True
  enable_dueling_dqn: True

flappybird_tutorial:
  env_id: FlappyBird-v0
  replay_memory_size: 10000
  batch_size: 32
  epsilon_init: 1.0
  epsilon_decay: 0.99995
  epsilon_min: 0.05
  network_sync_rate: 10
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: False